package controller.common;

import java.io.Serializable;

import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;


/**
 * 
 * съдържа конфигурационните настройки
 * 
 * TODO - да се четат от файл или от базата данни
 * 
 */
@SuppressWarnings("serial")
@ManagedBean(name="configurationProperties")
@ApplicationScoped
public class ConfigurationProperties implements Serializable {

	public static int getPageSize() {
		return 20;
	}
	
	public static String getElectronicShopID() {
		return "electronicShop1";
	}
	
	public static int getAutoGeneratedPasswordLength() {
		return 20;
	}
	
	public static int getAutoGeneratedCodeLength() {
		return 10;
	}
	
	public static int getWorkingTimeStartHour() {
		return 8;
	}
	
	public static int getWorkingTimeEndHour() {
		return 17;
	}
	
	public static int getAppointmentLenghtMinutes() {
		//NOTE: max 59 !!!
		return 30;
	}
	
}
