package controller.common;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.Serializable;
import java.util.Properties;

import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;


/**
 * 
 * съдържа конфигурационните настройки
 * 
 */
@SuppressWarnings("serial")
@ManagedBean(name="configurationProperties")
@ApplicationScoped
public class ConfigurationProperties implements Serializable {
	
	static Properties properties;
	
	static {
		properties = new Properties();
		
		try {
			properties.load(ConfigurationProperties.class.getClassLoader().getResourceAsStream("configuration.properties"));
		} catch (FileNotFoundException e) {
			throw new RuntimeException("Ooopsie", e);
		} catch (IOException e) {
			throw new RuntimeException("Ooopsie", e);
		}
	}

	public static int getPageSize() {
		return Integer.parseInt(properties.getProperty("pageSize"));
	}
	
	public static String getElectronicShopID() {
		return properties.getProperty("electronicShopID");
	}
	
	public static int getAutoGeneratedPasswordLength() {
		return Integer.parseInt(properties.getProperty("autoGeneratedPasswordLength"));
	}
	
	public static int getAutoGeneratedCodeLength() {
		return Integer.parseInt(properties.getProperty("autoGeneratedCodeLength"));
	}
	
	public static int getWorkingTimeStartHour() {
		return Integer.parseInt(properties.getProperty("workingTimeStartHour"));
	}
	
	public static int getWorkingTimeEndHour() {
		return Integer.parseInt(properties.getProperty("workingTimeEndHour"));
	}
	
	public static int getAppointmentLenghtMinutes() {
		//NOTE: max 59 !!!
		return Integer.parseInt(properties.getProperty("appointmentLenghtMinutes"));
	}
	
}
